apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: satmi-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: satmi-chatbot
      app.kubernetes.io/component: api
